// Combined Cloudflare Worker: SolidStart frontend + Durable Object backend.
// Build order: `vinxi build` first, then `wrangler deploy` bundles this file.

import solidHandler from '../.output/server/index.mjs';

export { ChatRoom } from './do/chat-room';
export { DmMailbox } from './do/dm-mailbox';
export { Registry } from './do/registry';

// ─── CORS ─────────────────────────────────────────────────────────────────────

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
} as const;

function withCors(res: Response): Response {
  if (res.status === 101) return res;
  const headers = new Headers(res.headers);
  for (const [k, v] of Object.entries(CORS_HEADERS)) headers.set(k, v);
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers });
}

function registry(env: Env): ReturnType<DurableObjectNamespace['get']> {
  return env.REGISTRY.get(env.REGISTRY.idFromName('global'));
}

// ─── Router ──────────────────────────────────────────────────────────────────

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);

    // /ws/{room} — chat room WebSocket
    const wsMatch = url.pathname.match(/^\/ws\/([^/]+)$/);
    if (wsMatch?.[1]) {
      const roomName = decodeURIComponent(wsMatch[1]).trim().slice(0, 64);
      if (!roomName) return new Response('Room name required', { status: 400 });
      const id = env.CHATROOM.idFromName(roomName);
      return env.CHATROOM.get(id).fetch(request);
    }

    // GET /registry — list all registered identity hashes
    if (url.pathname === '/registry' && request.method === 'GET') {
      return withCors(await registry(env).fetch(new Request(new URL('/list', url.origin))));
    }

    // /dm/{identityHash}/{action} — DM mailbox
    const dmMatch = url.pathname.match(/^\/dm\/([0-9a-f]{64})(\/.*)?$/);
    if (dmMatch) {
      if (request.method === 'OPTIONS') {
        return new Response(null, { status: 204, headers: CORS_HEADERS });
      }

      if (!dmMatch[1]) return new Response('Invalid identity hash', { status: 400 });
      const identityHash = dmMatch[1];
      const action = dmMatch[2] ?? '/';
      const id = env.DMMAILBOX.idFromName(identityHash);

      // /register: read body once, fan out to mailbox + registry
      if (action === '/register' && request.method === 'POST') {
        const body = (await request.json()) as { ecdsaPub: string; ecdhPub: string; username: string };
        const dmReq = new Request(new URL('/register', url.origin), {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ ecdsaPub: body.ecdsaPub, ecdhPub: body.ecdhPub }),
        });
        const res = await env.DMMAILBOX.get(id).fetch(dmReq);
        ctx.waitUntil(
          registry(env).fetch(
            new Request(new URL('/add', url.origin), {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                hash: identityHash,
                username: body.username ?? 'anonymous',
                ecdsaPub: body.ecdsaPub,
                ecdhPub: body.ecdhPub,
              }),
            }),
          ),
        );
        return withCors(res);
      }

      const rewritten = new Request(new URL(action, url.origin), request);
      return withCors(await env.DMMAILBOX.get(id).fetch(rewritten));
    }

    // All other routes → SolidStart (SSR + static assets)
    // @ts-expect-error - generated by `vinxi build`, not present at type-check time
    return (solidHandler as { fetch: typeof fetch }).fetch(request, env, ctx);
  },
} satisfies ExportedHandler<Env>;
